name: Clone on Push

on:
  push:
    branches:
      - main # Or whichever branch you want to trigger on

jobs:
  clone_repository:
    runs-on: ubuntu-22.04 # Or your preferred runner environment
    env:
      TEMP_DIR_ROOT: /mnt/target
    steps:
      - name: Check disk space before setting up
        run: df -BM

      - name: Reclaim some disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/hostedtoolcache

        # Empty /mnt on GitHub hosted runners
      - name: Empty /mnt directory
        # See https://github.com/orgs/community/discussions/75621
        # this seems to be the only way to (somewhat) reliably detected GitHub runners
        if: ${{ startsWith(runner.name, 'GitHub Actions') }}
        run: sudo rm -rf /mnt/* || true

      - name: Check disk space after freeing
        run: df -BM

      - name: Check what's in /mnt
        run: sudo ls /mnt

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'thin-edge/thin-edge.io'

      - name: Create target dir and symlink it to make caching behave sensibly
        run: sudo mkdir /mnt/target && sudo chmod 777 /mnt/target && ln -s target /mnt/target
    
      - name: Retrieve MSRV from workspace Cargo.toml
        id: rust_version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: Cargo.toml
          field: "workspace.package.rust-version"

      - name: Enable toolchain via github action
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Enable cache
        uses: Swatinem/rust-cache@v2

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: cargo llvm-cov
        run: cargo llvm-cov nextest --no-fail-fast --locked --all-features --all-targets --codecov --output-path codecov.json

      # https://github.com/rust-lang/cargo/issues/6669
      - name: cargo test --doc
        run: cargo test --locked --all-features --doc

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: Check disk space after completing workflow
        run: df -BM
